# Generated by Django 4.1.3 on 2022-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uclass', models.CharField(max_length=50)),
                ('div', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
